name: DaCHS Resource Test
run-name: Test repository against latest dachs
on:
  push:
    branches: [ "stable" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Repository content
      run: du -sh ${{ github.workspace }}/*
    - name: Pull DaCHS image (latest)
      run: docker pull gavodachs/dachs:latest
    - name: Run container
      run: |
        docker run --name dachs_container -v "${{ github.workspace }}:/var/gavo/inputs/planmap" -dt gavodachs/dachs
    - name: Start DaCHS
      run: |
        docker exec dachs_container /dachs.sh start
        
  Validate:
    needs: Setup
    steps:
      - name: Validate RD
        run: docker exec dachs_container dachs val planmap/q
        
  Import:
    needs: [Setup,Validate]
    steps:
      - name: Import RD (sample)
        run: docker exec dachs_container dachs imp -M 100 planmap/q
        
